# Generated by Django 4.1 on 2022-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
