# Generated by Django 4.1 on 2022-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
